### ISSUE TITLE
Request: Scope channel list by favoriteList?

### ISSUE THREAD

**Issue by olbjan** [nstrelow/ha_philips_2016#8]
I'm using this component with some success but there is one thing that annoys me:
In sources, it lists all TV/radio channels the TV receives. As I don't subscribe to payTV channels and don't watch a lot of other channels, I have created a favorite list on the TV that scopes this down to something like 48 channels out of 434 total.

The full TV channel list with the channel names get's pulled via https://tvip:1926/6/channeldb/tv/channelLists/all and the favorite list can be gotten via https://tvip:1926/6/channeldb/tv/favoriteLists/1 - unfortunately the favoriteLists/1 API endpoint only contains the ccid and preset and not the channel name.

As I'm unfortunately not a developer, I'm asking if it would be possible to extend the custom component to (optionally) scope the sources list down to only those channels (match via ccid) that are part of a favorite list (= favoriteLists/1 or optionally configure # of favoriteLists and iterate through /2, ... /x).

**Comment by nstrelow** [comment]
Good idea, this will have to wait some time. I will be abroad for an internship until October and will not have access to a TV.
But I think I can come up with something you could test

**Comment by olbjan** [comment]
I've hacked together a nasty addition to scope by favorite list. I'm sure this about as ugly as Python code gets and can probably be done in much fewer lines but it works and it's the first code I've written in 17 years and my first Python ever.

**Comment by nstrelow** [comment]
Wow, then I congratulate you on that :D

I will sure check it out and add some improvments if I find some ^^
